sudo: required
services:
  - docker

before_install:
  - docker build -t bradfordli/react-test -f ./client/Dockerfile.dev ./client

# Test running section
script:
  - docker run bradfordli/react-test npm run test --coverage --passWithNoTests


# build production versions and push to docker hub as well
after_success:
  - docker build -t bradfordli/multi-client ./client
  - docker build -t bradfordli/multi-nginx ./nginx
  - docker build -t bradfordli/multi-server ./server
  - docker build -t bradfordli/multi-worker ./worker
  # Login to DOcker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push bradfordli/multi-client
  - docker push bradfordli/multi-nginx
  - docker push bradfordli/multi-server
  - docker push bradfordli/multi-worker