sudo: required
services:
  - docker

before_install:
  - docker build -t liondancer/react-test -f ./client/Dockerfile.dev ./client

# Test running section
script:
  - docker run liondancer/react-test npm run test --coverage --passWithNoTests


# build production versions and push to docker hub as well
after_success:
  - docker build -t liondancer/multi-client ./client
  - docker build -t liondancer/multi-nginx ./nginx
  - docker build -t liondancer/multi-server ./server
  - docker build -t liondancer/multi-worker ./worker
  # Login to DOcker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push liondancer/multi-client
  - docker push liondancer/multi-nginx
  - docker push liondancer/multi-server
  - docker push liondancer/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-us-west-2-359605661627
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_PASSWORD
